## Import Libs

In [1]:
import pandas as pd
import requests

pd.set_option('display.max_columns', None)

## Dados Fato

In [2]:
df_saldo = pd.read_csv("https://www.bcb.gov.br/htms/sicor/DadosBrutos/SICOR_SALDOS_2025.gz", compression="gzip", delimiter=",")

KeyboardInterrupt:

In [3]:
df_operacao = pd.read_csv("https://www.bcb.gov.br/htms/sicor/DadosBrutos/SICOR_OPERACAO_BASICA_ESTADO_2025.gz", compression="gzip", delimiter=";")
# df_operacao_geral = pd.read_csv("https://www.bcb.gov.br/htms/sicor/DadosBrutos/SICOR_OPERACAO_BASICA_CONTRAT.gz", compression="gzip", delimiter=";")
# df_saldo = pd.read_csv("https://www.bcb.gov.br/htms/sicor/DadosBrutos/SICOR_SALDOS_2025.gz", compression="gzip", delimiter=",")

In [ ]:
print("Tabela 2025:", df_operacao.shape)
print("Tabela geral:", df_operacao_geral.shape)
print("Tabela geral:", df_saldo.shape)

Tabela 2025: (1841275, 47)
Tabela geral: (2449682, 44)

## Dados Dimensão

In [ ]:
df_recursos = pd.read_csv("https://www.bcb.gov.br/htms/sicor/FonteRecursos.csv", delimiter=",", encoding="latin1")
df_instancia = pd.read_csv("https://www.bcb.gov.br/htms/sicor/InstanciaProagro.csv", delimiter=",", encoding="latin1")
df_if = pd.read_csv("https://www.bcb.gov.br/htms/sicor/DadosBrutos/SICOR_LISTA_IFS.csv", delimiter=";", encoding="latin1")

In [34]:
df_operacao

,#REF_BACEN,NU_ORDEM,CNPJ_IF,DT_EMISSAO,DT_VENCIMENTO,CD_INST_CREDITO,CD_CATEG_EMITENTE,CD_FONTE_RECURSO,CNPJ_AGENTE_INVEST,CD_ESTADO,CD_REF_BACEN_INVESTIMENTO,CD_TIPO_SEGURO,CD_EMPREENDIMENTO,CD_PROGRAMA,CD_TIPO_ENCARG_FINANC,CD_TIPO_IRRIGACAO,CD_TIPO_AGRICULTURA,CD_FASE_CICLO_PRODUCAO,CD_TIPO_CULTIVO,CD_TIPO_INTGR_CONSOR,CD_TIPO_GRAO_SEMENTE,VL_ALIQ_PROAGRO,VL_JUROS,VL_PRESTACAO_INVESTIMENTO,VL_PREV_PROD,VL_QUANTIDADE,VL_RECEITA_BRUTA_ESPERADA,VL_PARC_CREDITO,VL_REC_PROPRIO,VL_PERC_RISCO_STN,VL_PERC_RISCO_FUNDO_CONST,VL_REC_PROPRIO_SRV,VL_AREA_FINANC,CD_SUBPROGRAMA,VL_PRODUTIV_OBTIDA,DT_FIM_COLHEITA,DT_FIM_PLANTIO,DT_INIC_COLHEITA,DT_INIC_PLANTIO,VL_JUROS_ENC_FINAN_POSFIX,VL_PERC_CUSTO_EFET_TOTAL,CD_CONTRATO_STN,CD_CNPJ_CADASTRANTE,VL_AREA_INFORMADA,CD_CICLO_CULTIVAR,CD_TIPO_SOLO,PC_BONUS_CAR
0,519338131,1,78483310,02/01/2025,17/01/2033,5,2222,403,NaN,SC,NaN,9,23271300193002,1,9,0,0,0,0,0,0,NaN,6.00,NaN,NaN,1.0,NaN,105000.0,0.0,NaN,NaN,NaN,0.03,2.0,NaN,NaN,NaN,NaN,NaN,NaN,6.08,2.024756e+12,2038232.0,0.03,NaN,NaN,NaN
1,519338131,2,78483310,02/01/2025,17/01/2033,5,2222,403,NaN,SC,NaN,9,23906240217408,1,9,0,0,0,0,0,0,NaN,6.00,NaN,NaN,1.0,NaN,25120.0,0.0,NaN,NaN,NaN,0.06,2.0,NaN,NaN,NaN,NaN,NaN,NaN,6.08,2.024756e+12,2038232.0,0.06,NaN,NaN,NaN
2,519338132,1,87733770,02/01/2025,15/11/2034,5,2222,403,NaN,RS,NaN,9,23705555108408,1,9,0,0,0,0,0,0,NaN,3.00,NaN,NaN,1.0,NaN,233333.0,NaN,NaN,NaN,NaN,2.06,52.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.024748e+12,1181521.0,2.06,NaN,NaN,NaN
3,519338133,1,78825023,02/01/2025,04/08/2025,5,2222,403,NaN,RS,NaN,2,12016940148043,1,9,1,3,22,0,2,0,8.0,3.00,NaN,65.0,NaN,162500.0,85000.0,0.0,NaN,NaN,9000.0,1.00,1.0,NaN,05/05/2025,30/01/2025,05/05/2025,15/01/2025,NaN,3.68,2.024756e+12,2038232.0,1.00,NaN,NaN,NaN
4,519338134,1,78825023,02/01/2025,13/08/2025,5,2222,403,NaN,RS,NaN,2,12016940148043,1,9,1,3,22,0,2,0,8.0,3.00,NaN,191.1,NaN,477750.0,249900.0,0.0,NaN,NaN,0.0,2.93,1.0,NaN,15/05/2025,30/01/2025,15/05/2025,25/01/2025,NaN,3.66,2.024756e+12,2038232.0,2.93,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1841270,521021440,1,7237373,30/10/2025,15/11/2033,5,2222,502,NaN,BA,NaN,9,13151820000002,999,9,0,0,0,0,0,0,NaN,8.63,NaN,NaN,1.0,NaN,93823.0,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.56,NaN,NaN,0.00,NaN,NaN,NaN
1841271,521021661,1,7237373,30/10/2025,15/11/2033,5,2222,502,NaN,MG,NaN,9,23144860116002,999,9,0,0,0,0,0,0,NaN,5.00,NaN,NaN,1.0,NaN,3420.0,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.99,NaN,NaN,0.00,NaN,NaN,NaN
1841272,521021805,1,7237373,30/10/2025,15/11/2033,5,2222,502,NaN,PE,NaN,9,13144860111002,999,9,0,0,0,0,0,0,NaN,8.63,NaN,NaN,1.0,NaN,17000.0,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.56,NaN,NaN,0.00,NaN,NaN,NaN
1841273,521021916,1,7237373,30/10/2025,15/11/2030,5,2222,502,NaN,PE,NaN,9,13144860247002,999,9,0,0,0,0,0,0,NaN,8.63,NaN,NaN,1.0,NaN,41400.0,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.55,NaN,NaN,0.00,NaN,NaN,NaN
1841274,521022015,1,7237373,30/10/2025,15/11/2032,5,2222,502,NaN,MG,NaN,9,23147080215002,999,9,0,0,0,0,0,0,NaN,8.63,NaN,NaN,1.0,NaN,190000.0,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.55,NaN,NaN,0.00,NaN,NaN,NaN

In [30]:
df_operacao.columns

Index(['#REF_BACEN', 'NU_ORDEM', 'CNPJ_IF', 'DT_EMISSAO', 'DT_VENCIMENTO',
       'CD_INST_CREDITO', 'CD_CATEG_EMITENTE', 'CD_FONTE_RECURSO',
       'CNPJ_AGENTE_INVEST', 'CD_ESTADO', 'CD_REF_BACEN_INVESTIMENTO',
       'CD_TIPO_SEGURO', 'CD_EMPREENDIMENTO', 'CD_PROGRAMA',
       'CD_TIPO_ENCARG_FINANC', 'CD_TIPO_IRRIGACAO', 'CD_TIPO_AGRICULTURA',
       'CD_FASE_CICLO_PRODUCAO', 'CD_TIPO_CULTIVO', 'CD_TIPO_INTGR_CONSOR',
       'CD_TIPO_GRAO_SEMENTE', 'VL_ALIQ_PROAGRO', 'VL_JUROS',
       'VL_PRESTACAO_INVESTIMENTO', 'VL_PREV_PROD', 'VL_QUANTIDADE',
       'VL_RECEITA_BRUTA_ESPERADA', 'VL_PARC_CREDITO', 'VL_REC_PROPRIO',
       'VL_PERC_RISCO_STN', 'VL_PERC_RISCO_FUNDO_CONST', 'VL_REC_PROPRIO_SRV',
       'VL_AREA_FINANC', 'CD_SUBPROGRAMA', 'VL_PRODUTIV_OBTIDA',
       'DT_FIM_COLHEITA', 'DT_FIM_PLANTIO', 'DT_INIC_COLHEITA',
       'DT_INIC_PLANTIO', 'VL_JUROS_ENC_FINAN_POSFIX',
       'VL_PERC_CUSTO_EFET_TOTAL', 'CD_CONTRATO_STN', 'CD_CNPJ_CADASTRANTE',
       'VL_AREA_INFORMADA', 'CD_CICLO_CULTIVAR', 'CD_TIPO_SOLO',
       'PC_BONUS_CAR'],
      dtype='object')

In [25]:
df_if.head()

   #CNPJ_IF                     NOME_IF             SEGMENTO_IF
0         0          BCO DO BRASIL S.A.           BANCO PÚBLICO
1       208  BRB - BCO DE BRASILIA S.A.           BANCO PÚBLICO
2     58338                   BOM CREDI  COOPERATIVA DE CRÉDITO
3     68987           CC ARACREDI LTDA.  COOPERATIVA DE CRÉDITO
4    204963                   CCR SEARA  COOPERATIVA DE CRÉDITO

In [18]:
df_recursos['DESCRICAO'].unique()

array(['RECURSOS LIVRES EQUALIZÁVEIS',
       'FACULDADE DE APLICAÇÃO - COMPULSÓRIO', 'TESOURO NACIONAL',
       'OBRIGATÓRIOS - MCR 6.2',
       'POUPANÇA RURAL - CONTROLADOS - SUBVENÇÃO ECONÔMICA',
       'POUPANÇA RURAL - CONTROLADOS - CONDIÇÕES MCR 6.2',
       'POUPANÇA RURAL - CONTROLADOS - FATOR DE PONDERAÇÃO',
       'POUPANÇA RURAL - LIVRE', 'RECURSOS LIVRES',
       'FUNDO DE COMMODITIES',
       'FUNDO CONSTITUCIONAL DE FINANCIAMENTO DO NORTE (FNO)',
       'FUNDO CONSTITUCIONAL DE FINANCIAMENTO DO NORDESTE (FNE)',
       'FUNDO CONSTITUCIONAL DE FINANCIAMENTO DO CENTRO-OESTE (FCO)',
       'BNDES/FINAME - EQUALIZÁVEL',
       'FAT - FUNDO DE AMPARO AO TRABALHADOR',
       'FUNCAFE-FUNDO DE DEFESA DA ECONOMIA CAFEEIRA',
       'FUNDO DE TERRAS E DA REFORMA AGRÁRIA', 'INCRA',
       'GOVERNOS E FUNDOS ESTADUAIS OU MUNICIPAIS', 'PIS/PASEP',
       'CAPTAÇÃO EXTERNA', 'OUTRAS FONTES DE RECURSOS NÃO ESPECIFICADAS',
       'ATIVIDADE NÃO FINANCIADA ENQUADRADA NO PROAGRO (MCR 16.8)',
       'INSTR HIBRIDO CAPITAL DÍVIDA-IHCD (Lei 12.793/2013 - Art. 6º) - EQUALIZÁVEL',
       'COMPULSÓRIO SOBRE RECURSOS À VISTA - REFORÇO DO INVESTIMENTO (CIRC 3.745)',
       'LETRA DE CRÉDITO DO AGRONEGÓCIO (LCA) - TAXA LIVRE',
       'BNDES LIVRE',
       'LETRA DE CRÉDITO DO AGRONEGÓCIO (LCA) - TAXA FAVORECIDA',
       'INSTR HIBRIDO CAPITAL DÍVIDA-IHCD (Lei 12.793/2013 - Art. 6º) - LIVRE',
       'Exigibilidade Adicional dos Recursos à Vista - Resolução 5030 ENCERRADO',
       'LETRA DE CRÉDITO DO AGRONEGÓCIO (LCA) - CONTROLADOS - SUBVENÇÃO ECONÔMICA - MCR 6-7-7A-b"-I"',
       'Exigibilidade Adicional dos Recursos à Vista - Resolução 5087 - ENCERRADO',
       'Exigibilidade Adicional dos Recursos à Vista - Resolução 5157',
       'EXIGIBILIDADE ADICIONAL DOS RECURSOS À VISTA',
       'EXIGIBILIDADE ADICIONAL DA POUPANÇA RURAL'], dtype=object)

In [5]:
df_operacao.describe()

,#REF_BACEN,NU_ORDEM,CNPJ_IF,CD_INST_CREDITO,CD_CATEG_EMITENTE,CD_FONTE_RECURSO,CNPJ_AGENTE_INVEST,CD_REF_BACEN_INVESTIMENTO,CD_TIPO_SEGURO,CD_EMPREENDIMENTO,CD_PROGRAMA,CD_TIPO_ENCARG_FINANC,CD_TIPO_IRRIGACAO,CD_TIPO_AGRICULTURA,CD_FASE_CICLO_PRODUCAO,CD_TIPO_CULTIVO,CD_TIPO_INTGR_CONSOR,CD_TIPO_GRAO_SEMENTE,VL_ALIQ_PROAGRO,VL_JUROS,VL_PRESTACAO_INVESTIMENTO,VL_PREV_PROD,VL_QUANTIDADE,VL_RECEITA_BRUTA_ESPERADA,VL_PARC_CREDITO,VL_REC_PROPRIO,VL_PERC_RISCO_STN,VL_PERC_RISCO_FUNDO_CONST,VL_REC_PROPRIO_SRV,VL_AREA_FINANC,CD_SUBPROGRAMA,VL_PRODUTIV_OBTIDA,VL_JUROS_ENC_FINAN_POSFIX,VL_PERC_CUSTO_EFET_TOTAL,CD_CONTRATO_STN,CD_CNPJ_CADASTRANTE,VL_AREA_INFORMADA,CD_CICLO_CULTIVAR,CD_TIPO_SOLO,PC_BONUS_CAR
count,1.983281e+06,1.983281e+06,1.983281e+06,1.983281e+06,1.983281e+06,1.983281e+06,3.827100e+04,3.827100e+04,1.983281e+06,1.983281e+06,1.983281e+06,1.983281e+06,1.983281e+06,1.983281e+06,1.983281e+06,1.983281e+06,1.983281e+06,1.983281e+06,196796.000000,1.983281e+06,38271.000000,6.839730e+05,1.597496e+06,6.839730e+05,1.983281e+06,6.123880e+05,1.467951e+06,1.503272e+06,177773.000000,1.980678e+06,1.659303e+06,4416.000000,4195.000000,1.646218e+06,4.646570e+05,3.728890e+05,1.980678e+06,326300.000000,326300.000000,32694.000000
mean,5.201698e+08,1.377121e+00,1.638207e+07,5.161798e+00,2.448035e+03,4.254952e+02,1.258606e+06,2.016705e+10,7.971854e+00,1.855434e+13,8.808302e+01,8.982877e+00,2.416571e-01,8.481093e-01,8.280164e+00,1.066914e-01,3.440894e-01,1.066550e+00,8.065910,3.959385e+00,4264.254407,4.356636e+05,1.085838e+04,4.688910e+05,1.514811e+05,3.264263e+04,1.183078e+00,7.033980e+01,5562.859614,1.534671e+01,4.252891e+01,2972.365933,8.580389,4.525116e+00,2.024701e+12,3.259035e+06,1.579309e+01,3.181569,8.696310,0.054720
std,4.825437e+05,8.066522e-01,2.747746e+07,1.831179e+00,5.587059e+02,1.157176e+02,7.256366e+06,1.011318e+09,2.427006e+00,5.209135e+12,2.714886e+02,3.394518e-01,8.209423e-01,1.980949e+00,1.649172e+01,9.856088e-01,7.578440e-01,2.689283e+00,3.565906,4.720660e+00,1328.615872,2.368838e+08,1.166040e+06,2.075877e+06,3.350279e+06,9.026389e+05,1.081241e+01,4.448412e+01,4034.058179,1.144582e+02,1.905726e+02,28842.884240,3.860993,7.419858e+00,5.539983e+08,5.232696e+06,1.206368e+02,5.636832,6.047407,0.156146
min,5.193381e+08,1.000000e+00,0.000000e+00,1.000000e+00,2.222000e+03,1.000000e+02,0.000000e+00,8.012198e+07,1.000000e+00,1.119158e+13,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.010000,0.000000e+00,0.000000e+00,7.350000e+01,1.000000e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,1.000000e+00,0.000000,0.000000,0.000000e+00,2.024001e+12,2.049630e+05,0.000000e+00,1.000000,0.000000,0.000000
25%,5.197556e+08,1.000000e+00,2.663426e+06,5.000000e+00,2.222000e+03,3.030000e+02,0.000000e+00,2.020104e+10,9.000000e+00,1.314084e+13,1.000000e+00,9.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.500000,5.000000e-01,4018.290000,5.324000e+01,1.000000e+00,7.183833e+04,6.000000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,2.000000e+00,0.000000,5.000000,5.000000e-01,2.024007e+12,1.181521e+06,0.000000e+00,1.000000,3.000000,0.000000
50%,5.201585e+08,1.000000e+00,7.237373e+06,5.000000e+00,2.222000e+03,5.020000e+02,0.000000e+00,2.022154e+10,9.000000e+00,2.231130e+13,1.000000e+00,9.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,7.900000,5.000000e-01,5000.000000,3.000000e+02,2.000000e+00,1.571335e+05,1.500000e+04,0.000000e+00,0.000000e+00,1.000000e+02,9000.000000,0.000000e+00,5.600000e+01,0.000000,8.500000,5.000000e-01,2.025001e+12,1.401771e+06,0.000000e+00,1.000000,12.000000,0.000000
75%,5.205885e+08,1.000000e+00,7.237373e+06,5.000000e+00,2.222000e+03,5.020000e+02,1.181521e+06,2.024101e+10,9.000000e+00,2.327130e+13,1.000000e+00,9.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,10.000000,6.500000e+00,5000.000000,1.800000e+04,1.400000e+01,3.740000e+05,8.000000e+04,1.000000e-02,0.000000e+00,1.000000e+02,9000.000000,5.130000e+00,5.600000e+01,3.892500,11.500000,6.600000e+00,2.025001e+12,2.038232e+06,5.240000e+00,2.000000,15.000000,0.000000
max,5.210335e+08,2.900000e+01,9.748928e+07,1.000000e+01,4.444000e+03,8.500000e+02,9.281656e+07,2.025162e+10,9.000000e+00,2.440084e+13,9.990000e+02,1.000000e+01,1.100000e+01,9.000000e+00,9.000000e+01,2.800000e+01,7.000000e+00,8.000000e+00,23.000000,1.000000e+02,5000.000000,1.620833e+11,6.005803e+08,6.407828e+08,3.000000e+09,2.287696e+08,1.000000e+02,1.000000e+02,9000.000000,4.277251e+04,6.792000e+03,904050.000000,22.850000,9.849300e+02,2.025948e+12,9.289492e+07,4.277262e+04,99.000000,16.000000,1.000000

In [ ]:
df_operacao["#REF_BACEN"].isnull().sum()

np.int64(0)