## Import Libs

In [2]:
import pandas as pd
import requests

pd.set_option('display.max_columns', None)

## Dados Fato

In [3]:
df_saldo = pd.read_csv("https://www.bcb.gov.br/htms/sicor/DadosBrutos/SICOR_SALDOS_2025.gz", compression="gzip", delimiter=",")

In [3]:
df_operacao = pd.read_csv("https://www.bcb.gov.br/htms/sicor/DadosBrutos/SICOR_OPERACAO_BASICA_ESTADO_2025.gz", compression="gzip", delimiter=";")
df_operacao_geral = pd.read_csv("https://www.bcb.gov.br/htms/sicor/DadosBrutos/SICOR_OPERACAO_BASICA_CONTRAT.gz", compression="gzip", delimiter=";")
df_saldo = pd.read_csv("https://www.bcb.gov.br/htms/sicor/DadosBrutos/SICOR_SALDOS_2025.gz", compression="gzip", delimiter=",")

URLError: <urlopen error [Errno 11001] getaddrinfo failed>

In [ ]:
print("Tabela 2025:", df_operacao.shape)
print("Tabela geral:", df_operacao_geral.shape)
print("Tabela geral:", df_saldo.shape)

Tabela 2025: (1841275, 47)
Tabela geral: (2449682, 44)

## Dados Dimensão

In [ ]:
df_recursos = pd.read_csv("https://www.bcb.gov.br/htms/sicor/FonteRecursos.csv", delimiter=",", encoding="latin1")
df_instancia = pd.read_csv("https://www.bcb.gov.br/htms/sicor/InstanciaProagro.csv", delimiter=",", encoding="latin1")
df_if = pd.read_csv("https://www.bcb.gov.br/htms/sicor/DadosBrutos/SICOR_LISTA_IFS.csv", delimiter=";", encoding="latin1")

In [34]:
df_operacao

,#REF_BACEN,NU_ORDEM,CNPJ_IF,DT_EMISSAO,DT_VENCIMENTO,CD_INST_CREDITO,CD_CATEG_EMITENTE,CD_FONTE_RECURSO,CNPJ_AGENTE_INVEST,CD_ESTADO,CD_REF_BACEN_INVESTIMENTO,CD_TIPO_SEGURO,CD_EMPREENDIMENTO,CD_PROGRAMA,CD_TIPO_ENCARG_FINANC,CD_TIPO_IRRIGACAO,CD_TIPO_AGRICULTURA,CD_FASE_CICLO_PRODUCAO,CD_TIPO_CULTIVO,CD_TIPO_INTGR_CONSOR,CD_TIPO_GRAO_SEMENTE,VL_ALIQ_PROAGRO,VL_JUROS,VL_PRESTACAO_INVESTIMENTO,VL_PREV_PROD,VL_QUANTIDADE,VL_RECEITA_BRUTA_ESPERADA,VL_PARC_CREDITO,VL_REC_PROPRIO,VL_PERC_RISCO_STN,VL_PERC_RISCO_FUNDO_CONST,VL_REC_PROPRIO_SRV,VL_AREA_FINANC,CD_SUBPROGRAMA,VL_PRODUTIV_OBTIDA,DT_FIM_COLHEITA,DT_FIM_PLANTIO,DT_INIC_COLHEITA,DT_INIC_PLANTIO,VL_JUROS_ENC_FINAN_POSFIX,VL_PERC_CUSTO_EFET_TOTAL,CD_CONTRATO_STN,CD_CNPJ_CADASTRANTE,VL_AREA_INFORMADA,CD_CICLO_CULTIVAR,CD_TIPO_SOLO,PC_BONUS_CAR
0,519338131,1,78483310,02/01/2025,17/01/2033,5,2222,403,NaN,SC,NaN,9,23271300193002,1,9,0,0,0,0,0,0,NaN,6.00,NaN,NaN,1.0,NaN,105000.0,0.0,NaN,NaN,NaN,0.03,2.0,NaN,NaN,NaN,NaN,NaN,NaN,6.08,2.024756e+12,2038232.0,0.03,NaN,NaN,NaN
1,519338131,2,78483310,02/01/2025,17/01/2033,5,2222,403,NaN,SC,NaN,9,23906240217408,1,9,0,0,0,0,0,0,NaN,6.00,NaN,NaN,1.0,NaN,25120.0,0.0,NaN,NaN,NaN,0.06,2.0,NaN,NaN,NaN,NaN,NaN,NaN,6.08,2.024756e+12,2038232.0,0.06,NaN,NaN,NaN
2,519338132,1,87733770,02/01/2025,15/11/2034,5,2222,403,NaN,RS,NaN,9,23705555108408,1,9,0,0,0,0,0,0,NaN,3.00,NaN,NaN,1.0,NaN,233333.0,NaN,NaN,NaN,NaN,2.06,52.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.024748e+12,1181521.0,2.06,NaN,NaN,NaN
3,519338133,1,78825023,02/01/2025,04/08/2025,5,2222,403,NaN,RS,NaN,2,12016940148043,1,9,1,3,22,0,2,0,8.0,3.00,NaN,65.0,NaN,162500.0,85000.0,0.0,NaN,NaN,9000.0,1.00,1.0,NaN,05/05/2025,30/01/2025,05/05/2025,15/01/2025,NaN,3.68,2.024756e+12,2038232.0,1.00,NaN,NaN,NaN
4,519338134,1,78825023,02/01/2025,13/08/2025,5,2222,403,NaN,RS,NaN,2,12016940148043,1,9,1,3,22,0,2,0,8.0,3.00,NaN,191.1,NaN,477750.0,249900.0,0.0,NaN,NaN,0.0,2.93,1.0,NaN,15/05/2025,30/01/2025,15/05/2025,25/01/2025,NaN,3.66,2.024756e+12,2038232.0,2.93,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1841270,521021440,1,7237373,30/10/2025,15/11/2033,5,2222,502,NaN,BA,NaN,9,13151820000002,999,9,0,0,0,0,0,0,NaN,8.63,NaN,NaN,1.0,NaN,93823.0,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.56,NaN,NaN,0.00,NaN,NaN,NaN
1841271,521021661,1,7237373,30/10/2025,15/11/2033,5,2222,502,NaN,MG,NaN,9,23144860116002,999,9,0,0,0,0,0,0,NaN,5.00,NaN,NaN,1.0,NaN,3420.0,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.99,NaN,NaN,0.00,NaN,NaN,NaN
1841272,521021805,1,7237373,30/10/2025,15/11/2033,5,2222,502,NaN,PE,NaN,9,13144860111002,999,9,0,0,0,0,0,0,NaN,8.63,NaN,NaN,1.0,NaN,17000.0,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.56,NaN,NaN,0.00,NaN,NaN,NaN
1841273,521021916,1,7237373,30/10/2025,15/11/2030,5,2222,502,NaN,PE,NaN,9,13144860247002,999,9,0,0,0,0,0,0,NaN,8.63,NaN,NaN,1.0,NaN,41400.0,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.55,NaN,NaN,0.00,NaN,NaN,NaN
1841274,521022015,1,7237373,30/10/2025,15/11/2032,5,2222,502,NaN,MG,NaN,9,23147080215002,999,9,0,0,0,0,0,0,NaN,8.63,NaN,NaN,1.0,NaN,190000.0,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.55,NaN,NaN,0.00,NaN,NaN,NaN

In [30]:
df_operacao.columns

Index(['#REF_BACEN', 'NU_ORDEM', 'CNPJ_IF', 'DT_EMISSAO', 'DT_VENCIMENTO',
       'CD_INST_CREDITO', 'CD_CATEG_EMITENTE', 'CD_FONTE_RECURSO',
       'CNPJ_AGENTE_INVEST', 'CD_ESTADO', 'CD_REF_BACEN_INVESTIMENTO',
       'CD_TIPO_SEGURO', 'CD_EMPREENDIMENTO', 'CD_PROGRAMA',
       'CD_TIPO_ENCARG_FINANC', 'CD_TIPO_IRRIGACAO', 'CD_TIPO_AGRICULTURA',
       'CD_FASE_CICLO_PRODUCAO', 'CD_TIPO_CULTIVO', 'CD_TIPO_INTGR_CONSOR',
       'CD_TIPO_GRAO_SEMENTE', 'VL_ALIQ_PROAGRO', 'VL_JUROS',
       'VL_PRESTACAO_INVESTIMENTO', 'VL_PREV_PROD', 'VL_QUANTIDADE',
       'VL_RECEITA_BRUTA_ESPERADA', 'VL_PARC_CREDITO', 'VL_REC_PROPRIO',
       'VL_PERC_RISCO_STN', 'VL_PERC_RISCO_FUNDO_CONST', 'VL_REC_PROPRIO_SRV',
       'VL_AREA_FINANC', 'CD_SUBPROGRAMA', 'VL_PRODUTIV_OBTIDA',
       'DT_FIM_COLHEITA', 'DT_FIM_PLANTIO', 'DT_INIC_COLHEITA',
       'DT_INIC_PLANTIO', 'VL_JUROS_ENC_FINAN_POSFIX',
       'VL_PERC_CUSTO_EFET_TOTAL', 'CD_CONTRATO_STN', 'CD_CNPJ_CADASTRANTE',
       'VL_AREA_INFORMADA', 'CD_CICLO_CULTIVAR', 'CD_TIPO_SOLO',
       'PC_BONUS_CAR'],
      dtype='object')

In [25]:
df_if.head()

   #CNPJ_IF                     NOME_IF             SEGMENTO_IF
0         0          BCO DO BRASIL S.A.           BANCO PÚBLICO
1       208  BRB - BCO DE BRASILIA S.A.           BANCO PÚBLICO
2     58338                   BOM CREDI  COOPERATIVA DE CRÉDITO
3     68987           CC ARACREDI LTDA.  COOPERATIVA DE CRÉDITO
4    204963                   CCR SEARA  COOPERATIVA DE CRÉDITO

In [18]:
df_recursos['DESCRICAO'].unique()

array(['RECURSOS LIVRES EQUALIZÁVEIS',
       'FACULDADE DE APLICAÇÃO - COMPULSÓRIO', 'TESOURO NACIONAL',
       'OBRIGATÓRIOS - MCR 6.2',
       'POUPANÇA RURAL - CONTROLADOS - SUBVENÇÃO ECONÔMICA',
       'POUPANÇA RURAL - CONTROLADOS - CONDIÇÕES MCR 6.2',
       'POUPANÇA RURAL - CONTROLADOS - FATOR DE PONDERAÇÃO',
       'POUPANÇA RURAL - LIVRE', 'RECURSOS LIVRES',
       'FUNDO DE COMMODITIES',
       'FUNDO CONSTITUCIONAL DE FINANCIAMENTO DO NORTE (FNO)',
       'FUNDO CONSTITUCIONAL DE FINANCIAMENTO DO NORDESTE (FNE)',
       'FUNDO CONSTITUCIONAL DE FINANCIAMENTO DO CENTRO-OESTE (FCO)',
       'BNDES/FINAME - EQUALIZÁVEL',
       'FAT - FUNDO DE AMPARO AO TRABALHADOR',
       'FUNCAFE-FUNDO DE DEFESA DA ECONOMIA CAFEEIRA',
       'FUNDO DE TERRAS E DA REFORMA AGRÁRIA', 'INCRA',
       'GOVERNOS E FUNDOS ESTADUAIS OU MUNICIPAIS', 'PIS/PASEP',
       'CAPTAÇÃO EXTERNA', 'OUTRAS FONTES DE RECURSOS NÃO ESPECIFICADAS',
       'ATIVIDADE NÃO FINANCIADA ENQUADRADA NO PROAGRO (MCR 16.8)',
       'INSTR HIBRIDO CAPITAL DÍVIDA-IHCD (Lei 12.793/2013 - Art. 6º) - EQUALIZÁVEL',
       'COMPULSÓRIO SOBRE RECURSOS À VISTA - REFORÇO DO INVESTIMENTO (CIRC 3.745)',
       'LETRA DE CRÉDITO DO AGRONEGÓCIO (LCA) - TAXA LIVRE',
       'BNDES LIVRE',
       'LETRA DE CRÉDITO DO AGRONEGÓCIO (LCA) - TAXA FAVORECIDA',
       'INSTR HIBRIDO CAPITAL DÍVIDA-IHCD (Lei 12.793/2013 - Art. 6º) - LIVRE',
       'Exigibilidade Adicional dos Recursos à Vista - Resolução 5030 ENCERRADO',
       'LETRA DE CRÉDITO DO AGRONEGÓCIO (LCA) - CONTROLADOS - SUBVENÇÃO ECONÔMICA - MCR 6-7-7A-b"-I"',
       'Exigibilidade Adicional dos Recursos à Vista - Resolução 5087 - ENCERRADO',
       'Exigibilidade Adicional dos Recursos à Vista - Resolução 5157',
       'EXIGIBILIDADE ADICIONAL DOS RECURSOS À VISTA',
       'EXIGIBILIDADE ADICIONAL DA POUPANÇA RURAL'], dtype=object)