In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [4]:
df = pd.read_csv("https://www.bcb.gov.br/htms/sicor/AliquotaBaseProagro.csv", delimiter=";")
df

,#MUN_CD,CATEGORIA_PRODUTO,TAXA_PREMIO,TSE_CD,DESCONTO_IRRIGACAO,DESCONTO_CULTIVO_PROTEGIDO,TAXA_AGROECOLOGICO_ORGANICO,TAXA_EQUILIBRIO,INICIO_VIGENCIA,FIM_VIGENCIA
0,50926,0,"10,00",2,"50,00","50,00","2,00","25,02",01/07/2024,NaN
1,1030,0,"10,00",2,"50,00","50,00","2,00","25,02",01/07/2024,NaN
2,50854,0,"10,00",2,"50,00","50,00","2,00","25,02",01/07/2024,NaN
3,50902,0,"10,00",2,"50,00","50,00","2,00","25,02",01/07/2024,NaN
4,35680,0,"10,00",2,"50,00","50,00","2,00","25,02",01/07/2024,NaN
...,...,...,...,...,...,...,...,...,...,...
200551,58430,13,"6,00",1,"50,00","50,00","4,00","3,00",01/07/2024,NaN
200552,58430,14,"7,00",1,"50,00","50,00","4,00","3,00",01/07/2024,NaN
200553,58430,15,"6,00",1,"50,00","50,00","4,00","3,00",01/07/2024,NaN
200554,58430,16,"5,90",1,"50,00","50,00","4,00","3,00",01/07/2024,NaN
200555,58430,17,"6,00",1,"50,00","50,00","4,00","4,34",01/07/2024,NaN

In [7]:
df = pd.read_csv("https://www.bcb.gov.br/htms/sicor/DadosBrutos/SICOR_OPERACAO_BASICA_ESTADO_2025.gz", compression="gzip", delimiter=";")

In [9]:
df.shape

(1587818, 47)

In [11]:
df[df["#REF_BACEN"] == 519338131]

,#REF_BACEN,NU_ORDEM,CNPJ_IF,DT_EMISSAO,DT_VENCIMENTO,CD_INST_CREDITO,CD_CATEG_EMITENTE,CD_FONTE_RECURSO,CNPJ_AGENTE_INVEST,CD_ESTADO,...,DT_INIC_COLHEITA,DT_INIC_PLANTIO,VL_JUROS_ENC_FINAN_POSFIX,VL_PERC_CUSTO_EFET_TOTAL,CD_CONTRATO_STN,CD_CNPJ_CADASTRANTE,VL_AREA_INFORMADA,CD_CICLO_CULTIVAR,CD_TIPO_SOLO,PC_BONUS_CAR
0,519338131,1,78483310,02/01/2025,17/01/2033,5,2222,403,NaN,SC,...,NaN,NaN,NaN,6.08,2.024756e+12,2038232.0,0.03,NaN,NaN,NaN
1,519338131,2,78483310,02/01/2025,17/01/2033,5,2222,403,NaN,SC,...,NaN,NaN,NaN,6.08,2.024756e+12,2038232.0,0.06,NaN,NaN,NaN

In [ ]:
#df1 = pd.read_csv("https://www.bcb.gov.br/htms/sicor/Empreendimento.csv", delimiter=";", encoding="latin1")
df2 = pd.read_csv("https://www.bcb.gov.br/htms/sicor/Atividade.csv", delimiter=",", encoding="latin1")
df3 = pd.read_csv("https://www.bcb.gov.br/htms/sicor/MunicipiosSicor.csv", delimiter=",", )

In [57]:
df3.head()

,#COD_MUNICIPIO_CADMU,NOME_MUNICIPIO,COD_MUNICIPIO_IBGE,COD_UF,NOME_UF,COD_UF_IBGE
0,39480,ROSÁRIO,2109601.0,MA,MARANHÃO,21.0
1,32889,LAGOA SALGADA,2406601.0,RN,RIO GRANDE DO NORTE,24.0
2,40338,CRUZÁLIA,3513306.0,SP,SÃO PAULO,35.0
3,8679,ANAURILÂNDIA,5000807.0,MS,MATO GROSSO DO SUL,50.0
4,55189,JOCA MARQUES,2205458.0,PI,PIAUÍ,22.0

In [4]:
agencia = 5630
conta = 864900

extrato = requests.get(f"https://api-extratos.bb.com.br/extratos/v1/conta-corrente/agencia/{agencia}/conta/{conta}")

ConnectionError: HTTPSConnectionPool(host='api-extratos.bb.com.br', port=443): Max retries exceeded with url: /extratos/v1/conta-corrente/agencia/5630/conta/864900 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x78978d32ef10>: Failed to resolve 'api-extratos.bb.com.br' ([Errno -2] Name or service not known)"))